version: '3.8'

services:
  # PostgreSQL Database with PGVector extension
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: arketic_database
    environment:
      POSTGRES_DB: arketic_db
      POSTGRES_USER: arketic_user
      POSTGRES_PASSWORD: arketic_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - arketic_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arketic_user -d arketic_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  arketic_network:
    driver: bridge